# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101i3bCfQo26oAraFjylkyK-4puyN8_EU
"""

# exercise 1
# author Jean Héricotte
#state : ongoing
